"""empty message

Revision ID: 522ffdc10918
Revises: 5f7c6d1f5a33
Create Date: 2025-08-01 10:55:14.932397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522ffdc10918'
down_revision = '5f7c6d1f5a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_column('vehicle_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorites_vehicle_id_fkey', 'vehicles', ['vehicle_id'], ['id'])

    # ### end Alembic commands ###
